import type { Metadata } from "next";
import { Inter, Irish_Grover } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

const InterFont = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const IrishGrover = Irish_Grover({
  variable: "--font-irish-grover",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Z-Animedex 2.0",
  description: "Generated by create next app by Chandev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${InterFont.variable} ${IrishGrover.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
